# Generated by Django 3.2 on 2022-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Сделано')], default='Новая', max_length=13, verbose_name='Статус')),
                ('created_at', models.DateField(default=None, null=True, verbose_name='Время окончания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
